# Display ascii art
print("\t.._______..")
print("\t./##\#/##\\.")
print("\t{|# o# o#|}")
print("\t{|#######|}")
print("\t.|#VVVVV#|.")
print("\t.\\#######/..")
print("\t...|##|...")
print("......###############......")
print("...../###############\\....")
